server:
  port: 8080
 
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/beifeng?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
 
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.beifeng.entity.dto
